In [25]:
import os
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [9]:
data_path = Path("datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1")

In [10]:
song_data_path = data_path / 'Music Info.csv'
user_data_path = data_path / 'User Listening History.csv'

In [12]:
df_songs = pd.read_csv(song_data_path)

In [13]:
df_songs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50683 entries, 0 to 50682
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   track_id             50683 non-null  object
 1   name                 50683 non-null  object
 2   artist               50683 non-null  object
 3   spotify_preview_url  50683 non-null  object
 4   spotify_id           50683 non-null  object
 5   tags                 49556 non-null  object
 6   genre                22348 non-null  object
 7   year                 50683 non-null  int64
 8   duration_ms          50683 non-null  int64
 9   danceability         50683 non-null  float64
 10  energy               50683 non-null  float64
 11  key                  50683 non-null  int64
 12  loudness             50683 non-null  float64
 13  mode                 50683 non-null  int64
 14  speechiness          50683 non-null  float64
 15  acousticness         50683 non-null  float64
 16  instrumentalness     50683 non-null  float64
 17  liveness             50683 non-null  float64
 18  valence              50683 non-null  float64
 19  tempo                50683 non-null  float64
 20  time_signature       50683 non-null  int64
dtypes: float64(9), int64(5), object(7)
memory usage: 8.1+ MB

In [14]:
df_songs.columns

Index(['track_id', 'name', 'artist', 'spotify_preview_url', 'spotify_id',
       'tags', 'genre', 'year', 'duration_ms', 'danceability', 'energy', 'key',
       'loudness', 'mode', 'speechiness', 'acousticness', 'instrumentalness',
       'liveness', 'valence', 'tempo', 'time_signature'],
      dtype='object')

In [15]:
df_songs.drop_duplicates(subset=['spotify_id','year','duration_ms'],inplace=True)

In [16]:
df_songs.duplicated(subset=['spotify_id','year','duration_ms']).sum()

0

In [17]:
df_songs.reset_index(drop=True,inplace=True)

In [ ]:
# some columns contain totally different values so removing them as no role on calculating similarity
rem_cols = ["spotify_preview_url","name","track_id","spotify_id","genre"]

df_col_filtering = df_songs.drop(columns=rem_cols)

In [ ]:
df_col_filtering.columns

Index(['artist', 'tags', 'year', 'duration_ms', 'danceability', 'energy',
       'key', 'loudness', 'mode', 'speechiness', 'acousticness',
       'instrumentalness', 'liveness', 'valence', 'tempo', 'time_signature'],
      dtype='object')

In [20]:
df_col_filtering.isna().sum()

artist                 0
tags                1126
year                   0
duration_ms            0
danceability           0
energy                 0
key                    0
loudness               0
mode                   0
speechiness            0
acousticness           0
instrumentalness       0
liveness               0
valence                0
tempo                  0
time_signature         0
dtype: int64

In [21]:
df_col_filtering.fillna({"tags" : "no_tags"},inplace=True)

In [22]:
df_col_filtering.isna().sum()

artist              0
tags                0
year                0
duration_ms         0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
dtype: int64

In [23]:
# most used tags
(
    df_songs
    .loc[:,"tags"]
    .str.lower()
    .str.split(',')
    .explode()
    .str.strip()
    .value_counts()
    .loc[lambda ser : ser >= 1000]
)

tags
rock            10681
indie            7284
electronic       6592
alternative      6271
pop              4650
                ...
ska              1088
gothic_metal     1072
grindcore        1040
french           1018
nu_metal         1006
Name: count, Length: 85, dtype: int64

In [26]:
! pip install category_encoders

Requirement already satisfied: category_encoders in /home/shashank/miniconda3/envs/insightflow/lib/python3.11/site-packages (2.9.0)
Requirement already satisfied: numpy>=1.14.0 in /home/shashank/miniconda3/envs/insightflow/lib/python3.11/site-packages (from category_encoders) (1.26.4)
Requirement already satisfied: pandas>=1.0.5 in /home/shashank/miniconda3/envs/insightflow/lib/python3.11/site-packages (from category_encoders) (2.2.3)
Requirement already satisfied: patsy>=0.5.1 in /home/shashank/miniconda3/envs/insightflow/lib/python3.11/site-packages (from category_encoders) (1.0.2)
Requirement already satisfied: scikit-learn>=1.6.0 in /home/shashank/miniconda3/envs/insightflow/lib/python3.11/site-packages (from category_encoders) (1.9.0)
Requirement already satisfied: scipy>=1.0.0 in /home/shashank/miniconda3/envs/insightflow/lib/python3.11/site-packages (from category_encoders) (1.17.1)
Requirement already satisfied: statsmodels>=0.9.0 in /home/shashank/miniconda3/envs/insightflow/lib/python3.11/site-packages (from category_encoders) (0.14.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/shashank/miniconda3/envs/insightflow/lib/python3.11/site-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/shashank/miniconda3/envs/insightflow/lib/python3.11/site-packages (from pandas>=1.0.5->category_encoders) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in /home/shashank/miniconda3/envs/insightflow/lib/python3.11/site-packages (from pandas>=1.0.5->category_encoders) (2026.2)
Requirement already satisfied: six>=1.5 in /home/shashank/miniconda3/envs/insightflow/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Requirement already satisfied: joblib>=1.4.0 in /home/shashank/miniconda3/envs/insightflow/lib/python3.11/site-packages (from scikit-learn>=1.6.0->category_encoders) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in /home/shashank/miniconda3/envs/insightflow/lib/python3.11/site-packages (from scikit-learn>=1.6.0->category_encoders) (2.22.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in /home/shashank/miniconda3/envs/insightflow/lib/python3.11/site-packages (from scikit-learn>=1.6.0->category_encoders) (3.6.0)
Requirement already satisfied: packaging>=21.3 in /home/shashank/miniconda3/envs/insightflow/lib/python3.11/site-packages (from statsmodels>=0.9.0->category_encoders) (26.0)

In [27]:
from sklearn.preprocessing import MinMaxScaler , StandardScaler , OneHotEncoder
from category_encoders.count import CountEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.compose import ColumnTransformer

In [30]:
df_col_filtering.head(2)

,artist,tags,year,duration_ms,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,The Killers,"rock, alternative, indie, alternative_rock, in...",2004,222200,0.355,0.918,1,-4.360,1,0.0746,0.001190,0.0,0.0971,0.240,148.114,4
1,Oasis,"rock, alternative, indie, pop, alternative_roc...",2006,258613,0.409,0.892,2,-4.373,1,0.0336,0.000807,0.0,0.2070,0.651,174.426,4

In [31]:
# columns to transform
frequency_encode_cols = ['year']
ohe_cols = ['artist','time_signature','key']
tfidf_cols = 'tags'
standard_scale_cols = ["duration_ms","loudness","tempo"]
min_max_scale_cols = ["danceability","energy","speechiness","acousticness","instrumentalness","liveness","valence"]

In [33]:
# data transformation pipeline

transformer = ColumnTransformer(transformers=[
    ("frequency_encode",CountEncoder(normalize=True,return_df=True),frequency_encode_cols),
    ("ohe",OneHotEncoder(handle_unknown="ignore"),ohe_cols),
    ("tfidf",TfidfVectorizer(max_features=85),tfidf_cols),
    ("standard_scale",StandardScaler(),standard_scale_cols),
    ("min_max_scale",MinMaxScaler(),min_max_scale_cols)
],remainder='passthrough',n_jobs=-1)

In [34]:

transformer

ColumnTransformer(n_jobs=-1, remainder='passthrough',
                  transformers=[('frequency_encode',
                                 CountEncoder(combine_min_nan_groups=True,
                                              normalize=True),
                                 ['year']),
                                ('ohe', OneHotEncoder(handle_unknown='ignore'),
                                 ['artist', 'time_signature', 'key']),
                                ('tfidf', TfidfVectorizer(max_features=85),
                                 'tags'),
                                ('standard_scale', StandardScaler(),
                                 ['duration_ms', 'loudness', 'tempo']),
                                ('min_max_scale', MinMaxScaler(),
                                 ['danceability', 'energy', 'speechiness',
                                  'acousticness', 'instrumentalness',
                                  'liveness', 'valence'])])

In [35]:
transformer.fit(df_col_filtering)

Warning: No categorical columns found. Calling 'transform' will only return input data.

ColumnTransformer(n_jobs=-1, remainder='passthrough',
                  transformers=[('frequency_encode',
                                 CountEncoder(combine_min_nan_groups=True,
                                              normalize=True),
                                 ['year']),
                                ('ohe', OneHotEncoder(handle_unknown='ignore'),
                                 ['artist', 'time_signature', 'key']),
                                ('tfidf', TfidfVectorizer(max_features=85),
                                 'tags'),
                                ('standard_scale', StandardScaler(),
                                 ['duration_ms', 'loudness', 'tempo']),
                                ('min_max_scale', MinMaxScaler(),
                                 ['danceability', 'energy', 'speechiness',
                                  'acousticness', 'instrumentalness',
                                  'liveness', 'valence'])])

In [ ]:
transformed_df = transformer.transform(df_col_filtering)

In [37]:
transformed_df.shape

(50674, 8431)

In [38]:
from sklearn.metrics.pairwise import cosine_similarity

In [39]:
# fetch a song where artist shakira
df_songs.loc[df_songs["artist"]=="Shakira"]

,track_id,name,artist,spotify_preview_url,spotify_id,tags,genre,year,duration_ms,danceability,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
1025,TRLWDVU128F932B093,"Whenever, Wherever",Shakira,https://p.scdn.co/mp3-preview/09ddeb4ae33ee6e8...,07PHBDuUmOeZ7jeKSbAbKi,"rock, pop, female_vocalists, singer_songwriter...",NaN,2012,196826,0.787,...,1,-4.967,0,0.0474,0.29800,0.000005,0.2060,0.860,107.674,4
2068,TRILOWN128F426080F,Underneath Your Clothes,Shakira,https://p.scdn.co/mp3-preview/6c5a56058ce04371...,07qRl4PT2lA6O3KN40McLz,"rock, pop, female_vocalists, singer_songwriter...",Pop,2013,224893,0.707,...,8,-5.293,1,0.0298,0.69100,0.000000,0.1030,0.407,82.784,4
2205,TRXLMFJ12903CC06F7,She Wolf,Shakira,https://p.scdn.co/mp3-preview/4dc802fd3b06fcb5...,075xFXR0JDBwFPVinG1ig5,"electronic, pop, female_vocalists, experimenta...",NaN,2009,187866,0.857,...,7,-6.480,1,0.0428,0.32300,0.003220,0.3140,0.868,121.994,4
2469,TRSQAWU128F92EA20F,La Tortura,Shakira,https://p.scdn.co/mp3-preview/e62ae4649f029729...,0ofDrTTcinCUxm7wqCLPQa,"electronic, pop, female_vocalists, singer_song...",Latin,2011,213106,0.741,...,0,-5.904,1,0.0421,0.02300,0.000788,0.1200,0.834,100.001,4
3373,TRINUNP12903CD84D9,Did It Again,Shakira,https://p.scdn.co/mp3-preview/5477eae2283113ff...,0eMNEdcC5OImvrfn79J9dU,"electronic, pop, female_vocalists, experimenta...",NaN,2009,227333,0.869,...,5,-5.069,0,0.0896,0.50900,0.000000,0.0741,0.599,137.955,4
4318,TROLUWR128F92E5858,Te Dejo Madrid,Shakira,https://p.scdn.co/mp3-preview/bcaccba847a5cf53...,0IESLhxv5iqXvMH5mm3z88,"pop, experimental, singer_songwriter, dance, l...",NaN,2001,187333,0.741,...,11,-5.011,1,0.0379,0.02440,0.000015,0.2830,0.926,131.017,4
4599,TRLNLES128F932DA8E,Fool,Shakira,https://p.scdn.co/mp3-preview/4ce283ae87d032f5...,0MttJjfO3pkTHJgVdXqPcP,"rock, pop, female_vocalists, acoustic, pop_rock",Rap,2001,230333,0.640,...,3,-5.848,1,0.0241,0.04560,0.000000,0.0988,0.420,100.994,4
4617,TRUIPZL12903CA0BFE,Rules,Shakira,https://p.scdn.co/mp3-preview/e5c557dc2b36006a...,1f7TZQzs4UikFQIzeWOtOj,"pop, female_vocalists, singer_songwriter, pop_...",NaN,2001,219106,0.692,...,5,-6.365,0,0.0418,0.03590,0.000002,0.1850,0.775,149.000,4
6046,TRAAKDG128F42A0ECB,Hips Don't Lie,Shakira,https://p.scdn.co/mp3-preview/3859547944f57cfb...,01Yj2MCGpjZs34PRlGgz4K,"pop, female_vocalists, singer_songwriter, danc...",Pop,2001,217453,0.777,...,10,-5.867,0,0.0734,0.28400,0.000000,0.4300,0.760,100.003,4
6818,TRBAHID128F4278EAF,Objection (Tango),Shakira,https://p.scdn.co/mp3-preview/bf65095d5ce58358...,0p9QhtUdbyDAQ6k14hQ2i3,"pop, female_vocalists, singer_songwriter, danc...",Pop,2001,222533,0.603,...,11,-5.282,0,0.0677,0.01470,0.000000,0.0246,0.705,179.344,4
7007,TRHEBDB128F92E9FC0,Don't Bother,Shakira,https://p.scdn.co/mp3-preview/d778abba87ff5de6...,08cuRs7v0vmBrYttD3BEPq,"rock, pop, female_vocalists, singer_songwriter...",Pop,2009,256800,0.620,...,7,-6.297,1,0.0420,0.00552,0.000990,0.1510,0.209,129.970,4
11904,TRADBSW128F933A7A8,Loba,Shakira,https://p.scdn.co/mp3-preview/8fd280cc8c535862...,1fPCGREltHJuV3axEPydLp,"electronic, pop, experimental, singer_songwrit...",NaN,2009,189200,0.853,...,7,-7.598,1,0.0451,0.40300,0.046000,0.0751,0.778,121.991,4
12305,TRYFVKK128F4240FE8,Why Wait,Shakira,https://p.scdn.co/mp3-preview/d78c90c5cb5626be...,0HiJFRxWme9myvUiDlqQ8q,"pop, experimental, singer_songwriter, dance",NaN,2001,221240,0.887,...,1,-5.535,0,0.0431,0.14400,0.000590,0.1230,0.399,129.943,4
12322,TROZGSI128F92EA0AE,La Pared,Shakira,https://p.scdn.co/mp3-preview/91217265ccb8fc80...,07xN9EAHMx7UVppVqSoPDF,"pop, experimental, singer_songwriter, piano",NaN,2005,199173,0.755,...,8,-7.101,1,0.0329,0.63800,0.003540,0.1020,0.615,129.015,4
16859,TRAFCNH12903CA072C,Inevitable,Shakira,https://p.scdn.co/mp3-preview/88da75b50a528fe6...,0d13t5pyd1kL6geJ5JnSjs,"rock, pop, singer_songwriter, 90s, acoustic, b...",NaN,2001,193440,0.641,...,6,-7.486,1,0.0621,0.23100,0.000083,0.1280,0.340,92.119,4
16945,TRUGCOP128F4232463,Si te vas,Shakira,https://p.scdn.co/mp3-preview/54633474ff7aafb1...,13wWKN82EOZze70szgY48s,"rock, pop, singer_songwriter, 90s, beautiful",NaN,1998,210600,0.676,...,2,-5.231,1,0.0407,0.04340,0.000000,0.3080,0.823,107.809,4
27040,TRSAGEK128F9333C7C,Lo Imprescindible,Shakira,https://p.scdn.co/mp3-preview/0b112235150f3381...,0ta0VCgTnBANe0fhXAYs0l,"pop, female_vocalists, german",NaN,2005,234866,0.697,...,9,-5.975,0,0.0309,0.23000,0.000001,0.3310,0.442,112.980,3
29943,TRUIESB128F427D70D,Tú,Shakira,https://p.scdn.co/mp3-preview/156365b8cbc625ee...,0XKKsfwzAhsLEKEDwARXX6,"pop, piano",NaN,2001,214546,0.569,...,0,-8.449,1,0.0254,0.68600,0.000002,0.2590,0.219,139.781,4
32180,TROSDVD12903CB116F,Mon Amour,Shakira,https://p.scdn.co/mp3-preview/3d0045ee2fddfb77...,0cwSydbpCned8mhZqTUHyb,"rock, pop, female_vocalists, singer_songwriter...",NaN,2001,245066,0.618,...,9,-2.848,0,0.1100,0.04320,0.000005,0.0989,0.421,144.008,4
38383,TRWUWRZ128F42ADA4A,Dreams for Plans,Shakira,https://p.scdn.co/mp3-preview/6e2c021846087a88...,2ObxMmMaDINr0ynkqW2BlY,"pop, female_vocalists, guitar, pop_rock",Pop,2005,242760,0.689,...,1,-7.427,1,0.0286,0.18000,0.000038,0.0844,0.548,96.098,4
38415,TRNHCIP128F42ADA54,Costume Makes the Clown,Shakira,https://p.scdn.co/mp3-preview/762595070b8b966d...,0R6MQ8AoHDcsg21xX0EWkZ,"rock, pop, female_vocalists, singer_songwriter...",NaN,2005,192133,0.537,...,8,-4.728,1,0.0374,0.05000,0.000000,0.1210,0.503,162.010,4
42428,TRGJXTC128F4278ECC,Que Me Quedes Tu,Shakira,https://p.scdn.co/mp3-preview/18c4b856a3a5c741...,1Gpb4mSdcDoFcOPajj8WKd,"pop, female_vocalists, pop_rock",Latin,2001,287333,0.765,...,7,-8.314,0,0.0271,0.27400,0.000071,0.2760,0.417,113.023,4
42446,TRCYQFE128F42ADA40,Animal City,Shakira,https://p.scdn.co/mp3-preview/23892da2ddc26b6c...,1gI8mnirWfPjh9jamSCNMW,"rock, pop, female_vocalists, singer_songwriter...",Pop,2005,195493,0.783,...,6,-4.407,0,0.1080,0.17100,0.000000,0.4350,0.893,140.039,4
42507,TRYTKQE128F42ADA50,Your Embrace,Shakira,https://p.scdn.co/mp3-preview/63b29a594f6d6976...,11pHuqmviC29FYrvFlj7ro,"pop, female_vocalists, love, mellow, pop_rock",Pop,2005,213000,0.427,...,0,-8.346,1,0.0470,0.33900,0.000000,0.3430,0.245,167.873,4
42555,TRFNIOO128F42AD944,Donde Estas Corazon,Shakira,https://p.scdn.co/mp3-preview/28b6b0789340e733...,16P23ucGLZUBMOa8rh9hZW,"female_vocalists, pop_rock",NaN,1996,231693,0.743,...,7,-9.212,1,0.0722,0.06350,0.000000,0.1260,0.597,109.044,4
43697,TRANQLL128F92F5263,Poem to a Horse,Shakira,https://p.scdn.co/mp3-preview/d6e5a567e639f673...,0QjOc0jrhT8DLSnkjwLlIy,"rock, pop, female_vocalists, pop_rock",Pop,2001,246426,0.644,...,11,-5.751,0,0.0377,0.02700,0.000004,0.1490,0.695,94.014,4
43705,TRIXHNL128F1496B61,Sale el Sol,Shakira,https://p.scdn.co/mp3-preview/83185ae92ade51e7...,0vuIlEP410klUy30tkNziu,"pop, female_vocalists, pop_rock",NaN,2010,200133,0.698,...,0,-5.925,1,0.0293,0.15500,0.000000,0.1030,0.257,119.006,4
43707,TRULZUZ128F427D869,Ready for the Good Times,Shakira,https://p.scdn.co/mp3-preview/cc7e2fa060501a1c...,0JiTG5OhLKlOXBuCGCbAKL,"pop, singer_songwriter, dance, pop_rock, drum_...",NaN,2001,253066,0.767,...,0,-6.249,0,0.0397,0.18400,0.001840,0.1140,0.829,121.003,4
43728,TRULHLZ128F42BB903,Illegal,Shakira,https://p.scdn.co/mp3-preview/fffbeba5d53973dc...,0N0DOF0MXnlFv3CdAk9cDb,"pop, female_vocalists, pop_rock",NaN,2005,233840,0.669,...,2,-8.662,1,0.0416,0.64500,0.000036,0.1120,0.609,147.949,4
43884,TRDENYV128F4295BF9,"Pies Descalzos, Sueños Blancos",Shakira,https://p.scdn.co/mp3-preview/079500681067456b...,0BBL6G7tp5z5h6JD23o53D,"rock, pop_rock",NaN,1996,205800,0.854,...,6,-7.333,0,0.0361,0.00854,0.000000,0.1520,0.673,119.957,4

In [40]:
def recommend(song_name, song_data, transformed_data, k=10):

    song_row = song_data.loc[song_data["name"] == song_name]

    if song_row.empty:
        print("Search Another Song")
        return None

    song_idx = song_row.index[0]

    input_vector = transformed_data[song_idx].reshape(1, -1)

    similarity_score = cosine_similarity(
        input_vector,
        transformed_data
    ).ravel()

    # Remove the searched song itself
    top_k_idx = np.argsort(similarity_score)[::-1]
    top_k_idx = top_k_idx[top_k_idx != song_idx][:k]

    recommendations = (
        song_data.iloc[top_k_idx]
        [['name', 'artist', 'spotify_preview_url']]
        .reset_index(drop=True)
    )

    return recommendations

In [42]:
f_df = recommend(
    "Despacito",
    df_songs,
    transformed_df,
    k=10
)

In [46]:
f_df.shape

(10, 3)