In [2]:
import numpy as np 
import pandas as pd 
from pathlib import Path
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler,StandardScaler,OneHotEncoder
from category_encoders.count import CountEncoder 
from sklearn.compose import ColumnTransformer

In [3]:
data_path = Path("datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1")
song_data_path = data_path / 'Music Info.csv'
user_data_path = data_path / 'User Listening History.csv'

In [4]:
df_songs = pd.read_csv(song_data_path)
df_songs.head()

,track_id,name,artist,spotify_preview_url,spotify_id,tags,genre,year,duration_ms,danceability,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,TRIOREW128F424EAF0,Mr. Brightside,The Killers,https://p.scdn.co/mp3-preview/4d26180e6961fd46...,09ZQ5TmUG8TSL56n0knqrj,"rock, alternative, indie, alternative_rock, in...",NaN,2004,222200,0.355,...,1,-4.360,1,0.0746,0.001190,0.000000,0.0971,0.240,148.114,4
1,TRRIVDJ128F429B0E8,Wonderwall,Oasis,https://p.scdn.co/mp3-preview/d012e536916c927b...,06UfBBDISthj1ZJAtX4xjj,"rock, alternative, indie, pop, alternative_roc...",NaN,2006,258613,0.409,...,2,-4.373,1,0.0336,0.000807,0.000000,0.2070,0.651,174.426,4
2,TROUVHL128F426C441,Come as You Are,Nirvana,https://p.scdn.co/mp3-preview/a1c11bb1cb231031...,0keNu0t0tqsWtExGM3nT1D,"rock, alternative, alternative_rock, 90s, grunge",RnB,1991,218920,0.508,...,4,-5.783,0,0.0400,0.000175,0.000459,0.0878,0.543,120.012,4
3,TRUEIND128F93038C4,Take Me Out,Franz Ferdinand,https://p.scdn.co/mp3-preview/399c401370438be4...,0ancVQ9wEcHVd0RrGICTE4,"rock, alternative, indie, alternative_rock, in...",NaN,2004,237026,0.279,...,9,-8.851,1,0.0371,0.000389,0.000655,0.1330,0.490,104.560,4
4,TRLNZBD128F935E4D8,Creep,Radiohead,https://p.scdn.co/mp3-preview/e7eb60e9466bc3a2...,01QoK9DA7VTeTSE3MNzp4I,"rock, alternative, indie, alternative_rock, in...",RnB,2008,238640,0.515,...,7,-9.935,1,0.0369,0.010200,0.000141,0.1290,0.104,91.841,4

# Data cleaning

In [5]:
df_songs.info()

<class 'pandas.DataFrame'>
RangeIndex: 50683 entries, 0 to 50682
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   track_id             50683 non-null  str
 1   name                 50683 non-null  str
 2   artist               50683 non-null  str
 3   spotify_preview_url  50683 non-null  str
 4   spotify_id           50683 non-null  str
 5   tags                 49556 non-null  str
 6   genre                22348 non-null  str
 7   year                 50683 non-null  int64
 8   duration_ms          50683 non-null  int64
 9   danceability         50683 non-null  float64
 10  energy               50683 non-null  float64
 11  key                  50683 non-null  int64
 12  loudness             50683 non-null  float64
 13  mode                 50683 non-null  int64
 14  speechiness          50683 non-null  float64
 15  acousticness         50683 non-null  float64
 16  instrumentalness     50683 non-null  float64
 17  liveness             50683 non-null  float64
 18  valence              50683 non-null  float64
 19  tempo                50683 non-null  float64
 20  time_signature       50683 non-null  int64
dtypes: float64(9), int64(5), str(7)
memory usage: 18.3 MB

In [6]:
df_songs['spotify_id'].duplicated().sum()

9

In [7]:
df_songs.drop_duplicates(subset=['spotify_id'],inplace=True)

In [8]:
df_songs.reset_index(drop=True,inplace=True)

In [9]:
# drop columns 
cols_to_rem = ['track_id','spotify_preview_url','spotify_id','genre','name']

df_filtered = df_songs.drop(columns=cols_to_rem)

In [10]:
df_filtered.head()

,artist,tags,year,duration_ms,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,The Killers,"rock, alternative, indie, alternative_rock, in...",2004,222200,0.355,0.918,1,-4.360,1,0.0746,0.001190,0.000000,0.0971,0.240,148.114,4
1,Oasis,"rock, alternative, indie, pop, alternative_roc...",2006,258613,0.409,0.892,2,-4.373,1,0.0336,0.000807,0.000000,0.2070,0.651,174.426,4
2,Nirvana,"rock, alternative, alternative_rock, 90s, grunge",1991,218920,0.508,0.826,4,-5.783,0,0.0400,0.000175,0.000459,0.0878,0.543,120.012,4
3,Franz Ferdinand,"rock, alternative, indie, alternative_rock, in...",2004,237026,0.279,0.664,9,-8.851,1,0.0371,0.000389,0.000655,0.1330,0.490,104.560,4
4,Radiohead,"rock, alternative, indie, alternative_rock, in...",2008,238640,0.515,0.430,7,-9.935,1,0.0369,0.010200,0.000141,0.1290,0.104,91.841,4

In [11]:
df_filtered.columns

Index(['artist', 'tags', 'year', 'duration_ms', 'danceability', 'energy',
       'key', 'loudness', 'mode', 'speechiness', 'acousticness',
       'instrumentalness', 'liveness', 'valence', 'tempo', 'time_signature'],
      dtype='str')

In [12]:
df_filtered.isna().sum()

artist                 0
tags                1126
year                   0
duration_ms            0
danceability           0
energy                 0
key                    0
loudness               0
mode                   0
speechiness            0
acousticness           0
instrumentalness       0
liveness               0
valence                0
tempo                  0
time_signature         0
dtype: int64

In [13]:
df_filtered.fillna({"tags" : "no_tags"},inplace=True)

,artist,tags,year,duration_ms,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,The Killers,"rock, alternative, indie, alternative_rock, in...",2004,222200,0.355,0.918,1,-4.360,1,0.0746,0.001190,0.000000,0.0971,0.240,148.114,4
1,Oasis,"rock, alternative, indie, pop, alternative_roc...",2006,258613,0.409,0.892,2,-4.373,1,0.0336,0.000807,0.000000,0.2070,0.651,174.426,4
2,Nirvana,"rock, alternative, alternative_rock, 90s, grunge",1991,218920,0.508,0.826,4,-5.783,0,0.0400,0.000175,0.000459,0.0878,0.543,120.012,4
3,Franz Ferdinand,"rock, alternative, indie, alternative_rock, in...",2004,237026,0.279,0.664,9,-8.851,1,0.0371,0.000389,0.000655,0.1330,0.490,104.560,4
4,Radiohead,"rock, alternative, indie, alternative_rock, in...",2008,238640,0.515,0.430,7,-9.935,1,0.0369,0.010200,0.000141,0.1290,0.104,91.841,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50669,アンティック-珈琲店-,no_tags,2008,273440,0.438,0.933,6,-3.062,0,0.1650,0.003120,0.000000,0.1300,0.421,166.956,4
50670,ACIDMAN,"rock, alternative_rock, japanese, cover",2004,275133,0.351,0.693,0,-6.811,1,0.1200,0.000940,0.000049,0.1920,0.450,200.350,4
50671,coldrain,"metal, metalcore, post_hardcore",2014,254826,0.434,0.975,10,-3.092,0,0.2680,0.000108,0.001410,0.1630,0.282,158.025,4
50672,アンティック-珈琲店-,no_tags,2008,243293,0.513,0.902,4,-3.914,0,0.0530,0.000715,0.001350,0.0571,0.618,109.923,4
50673,9mm Parabellum Bullet,"rock, japanese",2008,131960,0.190,0.953,8,-4.144,1,0.1310,0.000033,0.051100,0.2030,0.138,136.475,4

In [14]:
df_filtered.head()

,artist,tags,year,duration_ms,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,The Killers,"rock, alternative, indie, alternative_rock, in...",2004,222200,0.355,0.918,1,-4.360,1,0.0746,0.001190,0.000000,0.0971,0.240,148.114,4
1,Oasis,"rock, alternative, indie, pop, alternative_roc...",2006,258613,0.409,0.892,2,-4.373,1,0.0336,0.000807,0.000000,0.2070,0.651,174.426,4
2,Nirvana,"rock, alternative, alternative_rock, 90s, grunge",1991,218920,0.508,0.826,4,-5.783,0,0.0400,0.000175,0.000459,0.0878,0.543,120.012,4
3,Franz Ferdinand,"rock, alternative, indie, alternative_rock, in...",2004,237026,0.279,0.664,9,-8.851,1,0.0371,0.000389,0.000655,0.1330,0.490,104.560,4
4,Radiohead,"rock, alternative, indie, alternative_rock, in...",2008,238640,0.515,0.430,7,-9.935,1,0.0369,0.010200,0.000141,0.1290,0.104,91.841,4

In [15]:
df_filtered["songs_text"] = (
    "Artist: " + df_filtered['artist'] +
    ".  Tags: " + df_filtered['tags'] 
)

In [16]:
df_filtered

,artist,tags,year,duration_ms,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,songs_text
0,The Killers,"rock, alternative, indie, alternative_rock, in...",2004,222200,0.355,0.918,1,-4.360,1,0.0746,0.001190,0.000000,0.0971,0.240,148.114,4,"Artist: The Killers. Tags: rock, alternative,..."
1,Oasis,"rock, alternative, indie, pop, alternative_roc...",2006,258613,0.409,0.892,2,-4.373,1,0.0336,0.000807,0.000000,0.2070,0.651,174.426,4,"Artist: Oasis. Tags: rock, alternative, indie..."
2,Nirvana,"rock, alternative, alternative_rock, 90s, grunge",1991,218920,0.508,0.826,4,-5.783,0,0.0400,0.000175,0.000459,0.0878,0.543,120.012,4,"Artist: Nirvana. Tags: rock, alternative, alt..."
3,Franz Ferdinand,"rock, alternative, indie, alternative_rock, in...",2004,237026,0.279,0.664,9,-8.851,1,0.0371,0.000389,0.000655,0.1330,0.490,104.560,4,"Artist: Franz Ferdinand. Tags: rock, alternat..."
4,Radiohead,"rock, alternative, indie, alternative_rock, in...",2008,238640,0.515,0.430,7,-9.935,1,0.0369,0.010200,0.000141,0.1290,0.104,91.841,4,"Artist: Radiohead. Tags: rock, alternative, i..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50669,アンティック-珈琲店-,no_tags,2008,273440,0.438,0.933,6,-3.062,0,0.1650,0.003120,0.000000,0.1300,0.421,166.956,4,Artist: アンティック-珈琲店-. Tags: no_tags
50670,ACIDMAN,"rock, alternative_rock, japanese, cover",2004,275133,0.351,0.693,0,-6.811,1,0.1200,0.000940,0.000049,0.1920,0.450,200.350,4,"Artist: ACIDMAN. Tags: rock, alternative_rock..."
50671,coldrain,"metal, metalcore, post_hardcore",2014,254826,0.434,0.975,10,-3.092,0,0.2680,0.000108,0.001410,0.1630,0.282,158.025,4,"Artist: coldrain. Tags: metal, metalcore, pos..."
50672,アンティック-珈琲店-,no_tags,2008,243293,0.513,0.902,4,-3.914,0,0.0530,0.000715,0.001350,0.0571,0.618,109.923,4,Artist: アンティック-珈琲店-. Tags: no_tags
50673,9mm Parabellum Bullet,"rock, japanese",2008,131960,0.190,0.953,8,-4.144,1,0.1310,0.000033,0.051100,0.2030,0.138,136.475,4,"Artist: 9mm Parabellum Bullet. Tags: rock, ja..."

In [17]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer(
"sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
)

text_vectors = model.encode(
    df_filtered["songs_text"].tolist(),
    batch_size=64,
    show_progress_bar=True
)

/home/shashank/miniconda3/envs/insightflow/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 4045.22it/s]
Batches: 100%|██████████| 792/792 [01:18<00:00, 10.12it/s]

In [18]:
display(text_vectors.shape , type(text_vectors))

(50674, 384)

numpy.ndarray

In [19]:
text_vectors[0]

array([-4.25492227e-02, -3.08130324e-01,  1.02395482e-01,  3.22657883e-01,
        1.80543259e-01,  2.99176395e-01,  7.64449909e-02, -2.15240363e-02,
       -5.50147817e-02,  1.12826295e-01,  3.77163589e-01, -4.09635693e-01,
        7.52773210e-02, -2.15774938e-01,  2.68301070e-01,  1.24700092e-01,
        6.07537627e-02, -5.48639931e-02,  1.76300153e-01,  6.70837378e-03,
       -9.96436849e-02,  3.68497781e-02,  2.58368492e-01, -5.03956266e-02,
       -2.20713541e-01, -1.77173302e-01, -1.45910040e-01,  3.04876745e-01,
       -1.71406195e-01, -2.19145745e-01,  1.29406705e-01,  2.12752625e-01,
        1.39316292e-02, -4.70237248e-02,  1.05124831e-01,  8.99814218e-02,
       -1.41633362e-01,  3.90709847e-01, -3.16439956e-01, -2.02997088e-01,
       -3.08420183e-03,  1.55789495e-01, -4.39189672e-02, -6.90413564e-02,
       -1.86408922e-01, -3.58773679e-01, -1.05552733e-01, -2.14744918e-02,
       -3.85159224e-01, -1.29936263e-01,  7.94593915e-02, -2.30884962e-02,
        4.49857209e-03, -1.31690800e-02, -1.26613930e-01, -6.12289310e-01,
       -1.46614298e-01,  2.87747681e-01,  1.99990824e-01, -4.28654738e-02,
        1.69561073e-01, -2.19421729e-01, -4.95039612e-01,  2.58873135e-01,
        3.26245241e-02, -9.29029949e-04,  2.27878019e-01, -6.79253116e-02,
       -1.25401765e-01,  1.13314971e-01,  2.26336926e-01,  9.70639363e-02,
        1.13152862e-01, -2.64176905e-01,  1.55340424e-02, -1.92829333e-02,
        2.21184164e-01, -2.13287219e-01, -2.32354999e-01, -1.44371033e-01,
       -2.14335129e-01, -1.76312283e-01, -3.26040611e-02, -3.28472525e-01,
       -1.59478977e-01,  9.24063697e-02, -1.64905146e-01,  2.97319829e-01,
       -1.39267772e-01,  1.17759861e-01, -3.96947354e-01, -7.41402954e-02,
        2.65167564e-01, -1.42522201e-01,  4.14357245e-01,  8.44718888e-02,
       -7.29101151e-02,  2.04670414e-01, -5.44437170e-02,  4.28987771e-01,
        1.12096615e-01,  2.52440274e-01, -2.68341571e-01,  1.60796538e-01,
        1.52290925e-01,  4.64617740e-03,  1.10228874e-01,  1.05858082e-02,
       -1.26007661e-01, -9.58937332e-02,  9.34098884e-02,  5.84913709e-04,
        8.78420658e-03, -3.02558184e-01,  1.68305531e-01, -3.24245542e-01,
       -3.73402119e-01,  1.59440368e-01,  2.49970645e-01,  1.42001912e-01,
        2.86404073e-01,  1.00915566e-01,  1.10396676e-01,  2.39912614e-01,
        1.35083959e-01, -8.29057172e-02, -2.43384972e-01, -2.87544746e-02,
        1.93954811e-01,  1.01013012e-01,  1.01132594e-01, -7.11216256e-02,
        4.46780205e-01, -4.92044631e-03, -3.04600507e-01,  2.00874940e-01,
       -1.53592145e-02,  1.41167507e-01,  1.23676024e-01,  5.80729507e-02,
        4.95666191e-02, -5.70719503e-02, -3.64553005e-01, -9.41318944e-02,
        2.87499666e-01,  1.95847705e-01, -4.50981334e-02, -6.39513135e-03,
       -3.24034870e-01,  5.75887978e-01, -6.68863803e-02, -2.20695660e-01,
        1.30982608e-01,  2.35357415e-02, -1.13338985e-01,  8.43658447e-02,
        4.53315705e-01, -3.47286575e-02, -1.19348563e-01,  6.76135644e-02,
        2.16420844e-01,  1.32322147e-01,  1.49335321e-02,  1.84012845e-01,
       -2.02594344e-02, -2.92791277e-01, -1.69639602e-01,  6.64560944e-02,
        5.49532697e-02,  1.65392473e-01, -1.79914340e-01, -1.78594608e-02,
        1.64245795e-02,  2.76600897e-01, -1.29142091e-01,  2.55530536e-01,
        6.57041222e-02, -3.28217782e-02, -1.11430593e-01, -2.01742854e-02,
       -2.83728559e-02,  4.33286242e-02, -3.73891085e-01,  1.69972330e-02,
       -4.76184040e-01, -5.11110462e-02,  1.59953430e-01,  7.31456429e-02,
        1.46522895e-01,  2.88190097e-01,  9.61250998e-03, -1.74198747e-01,
        4.02294770e-02,  1.22361250e-01,  1.35406941e-01, -6.67522401e-02,
        1.67506665e-01,  1.37908414e-01, -2.79355377e-01, -9.58981514e-02,
       -5.91959171e-02,  3.42940301e-01,  9.60472450e-02, -2.17749365e-02,
       -1.12779535e-01,  1.52169898e-01,  2.34258100e-01,  1.31556720e-01,
       -1.70518562e-01,  5.06503880e-03, -3.71452063e-01, -1.28536627e-01,
       -6.76196069e-02, -5.41665182e-02, -6.85644969e-02, -6.26184285e-01,
       -1.06176749e-01,  6.90478319e-03, -5.06484509e-01, -1.23038441e-02,
        1.08804442e-01, -1.37825340e-01, -2.67177165e-01, -2.31163949e-01,
        3.15035023e-02, -1.14814825e-01, -1.95714504e-01,  7.21097440e-02,
       -2.10700616e-01,  1.39323428e-01, -3.36186945e-01,  1.65203333e-01,
        3.36967289e-01,  8.30132365e-02, -2.26074383e-01,  3.86428647e-02,
        1.79020479e-01, -2.06599310e-01,  1.31199822e-01, -2.12881520e-01,
       -4.45866734e-01,  5.96306249e-02,  1.19138770e-01,  2.05296203e-01,
       -2.19290286e-01, -1.14516295e-01, -6.74478039e-02,  2.70337611e-01,
        2.90884495e-01,  3.41033995e-01,  1.61415771e-01,  2.18853638e-01,
        1.03083983e-01,  3.49708162e-02,  3.16857666e-01,  4.35086042e-01,
       -1.85912132e-01, -7.51569942e-02, -1.38476327e-01,  6.00162484e-02,
       -1.01459689e-01, -1.42719045e-01,  7.95416161e-02,  1.63441315e-01,
        5.25223240e-02,  1.50151253e-02, -2.22549438e-01,  1.81739137e-01,
       -9.19901803e-02, -1.96863011e-01, -1.24088787e-01,  2.31141433e-01,
       -5.72200418e-02, -3.35017473e-01,  2.09726132e-02, -3.02173346e-01,
       -8.08984488e-02, -5.27887344e-01,  1.11657530e-02,  9.94914956e-03,
        2.20210999e-01, -1.54018089e-01,  3.72431546e-01,  2.46961668e-01,
       -1.76932171e-01,  2.13078573e-01, -1.19747460e-01, -2.55972415e-01,
       -3.14285100e-01,  4.82639261e-02, -1.56821594e-01,  3.37881185e-02,
       -3.69818062e-01, -5.70453592e-02, -4.06554341e-02,  1.18671857e-01,
       -3.15537900e-01, -9.24363509e-02, -8.57764930e-02, -5.14910044e-03,
        9.55190286e-02, -4.29631537e-03,  1.52010461e-02, -3.87472361e-01,
        5.13061106e-01,  8.10855627e-02, -1.03934102e-01,  2.94609517e-01,
        2.41309762e-01,  3.88114959e-01, -3.36523987e-02,  2.01036900e-01,
       -8.74061212e-02,  4.79342416e-02, -3.29525881e-02, -3.31801713e-01,
        1.81565180e-01,  1.14832886e-01, -3.05334598e-01, -1.41977191e-01,
       -8.09467304e-03,  3.90569955e-01, -9.17123184e-02,  9.00575295e-02,
        1.21731265e-02,  5.75352013e-01,  5.20095415e-02, -1.00853242e-01,
       -1.29211530e-01,  2.53982395e-01, -7.23676533e-02, -1.09809481e-01,
        2.61342525e-01,  2.04369932e-01, -1.90049857e-01,  5.82497381e-02,
       -3.04179847e-01, -5.18914238e-02, -1.02876663e-01, -7.34748617e-02,
        8.65411088e-02, -5.51487990e-02,  3.25685516e-02, -2.39067063e-01,
        1.45094646e-02, -1.77845210e-01,  1.54295295e-01, -2.28345662e-01,
        8.68419185e-02,  1.82319656e-01,  8.87952223e-02,  2.81929702e-01,
       -8.45086053e-02,  4.13901027e-04, -2.23602951e-02, -2.10717082e-01,
        7.16139302e-02,  8.85602757e-02,  1.62545308e-01,  2.76531409e-02,
        5.19495346e-02,  8.09291601e-02,  3.74706686e-02,  8.73726457e-02,
       -2.18777806e-01, -1.56405717e-01,  3.34551841e-01,  2.22757474e-01,
       -1.75517485e-01, -1.88542947e-01, -4.29625772e-02, -2.80368298e-01,
       -1.79122180e-01,  1.89440161e-01,  1.83349639e-01, -2.41178200e-01,
        4.98432154e-03,  3.06783170e-01, -2.27046043e-01,  1.55640602e-01,
        4.08319682e-01, -1.97348624e-01,  1.64326310e-01, -1.39979655e-02],
      dtype=float32)

In [20]:
col_already_used = ['artist','tags','songs_text']

df_filtered.drop(columns=col_already_used,inplace=True)

In [21]:
standard_scale_cols = ["duration_ms","loudness","tempo"]
ohe_cols = ['time_signature','key']
min_max_scale_cols = ["danceability","energy","speechiness","acousticness","instrumentalness","liveness","valence","year"]

In [22]:
# data transformation pipeline

transformer = ColumnTransformer(transformers=[
    ("ohe",OneHotEncoder(handle_unknown="ignore"),ohe_cols),
    ("standard_scale",StandardScaler(),standard_scale_cols),
    ("min_max_scale",MinMaxScaler(),min_max_scale_cols)
],remainder='passthrough',n_jobs=-1)

In [23]:
transformer

ColumnTransformer(n_jobs=-1, remainder='passthrough',
                  transformers=[('ohe', OneHotEncoder(handle_unknown='ignore'),
                                 ['time_signature', 'key']),
                                ('standard_scale', StandardScaler(),
                                 ['duration_ms', 'loudness', 'tempo']),
                                ('min_max_scale', MinMaxScaler(),
                                 ['danceability', 'energy', 'speechiness',
                                  'acousticness', 'instrumentalness',
                                  'liveness', 'valence', 'year'])])

In [24]:
transformer.fit(df_filtered)

ColumnTransformer(n_jobs=-1, remainder='passthrough',
                  transformers=[('ohe', OneHotEncoder(handle_unknown='ignore'),
                                 ['time_signature', 'key']),
                                ('standard_scale', StandardScaler(),
                                 ['duration_ms', 'loudness', 'tempo']),
                                ('min_max_scale', MinMaxScaler(),
                                 ['danceability', 'energy', 'speechiness',
                                  'acousticness', 'instrumentalness',
                                  'liveness', 'valence', 'year'])])

In [25]:
transformed_df = transformer.transform(df_filtered)

In [26]:
type(transformed_df)

numpy.ndarray

In [27]:
transformed_df.shape

(50674, 29)

In [28]:
from sklearn.preprocessing import normalize
#normalize audio vector
audio_features = normalize(
    transformed_df,
    norm="l2"
)

# normalize MiniLM vectors
text_embeddings = normalize(
    text_vectors,
    norm="l2"
)

In [29]:
final_embedding = np.concatenate(
    [
        text_embeddings * 0.2,
        audio_features * 0.8
    ],
    axis=1
)
final_embeddings = final_embedding.astype(
    "float32"
)

In [30]:
! pip install faiss-cpu

Requirement already satisfied: faiss-cpu in /home/shashank/miniconda3/envs/insightflow/lib/python3.11/site-packages (1.14.2)
Requirement already satisfied: numpy>=1.25 in /home/shashank/miniconda3/envs/insightflow/lib/python3.11/site-packages (from faiss-cpu) (1.26.4)
Requirement already satisfied: packaging in /home/shashank/miniconda3/envs/insightflow/lib/python3.11/site-packages (from faiss-cpu) (26.0)

In [31]:
import faiss

dimension = final_embeddings.shape[1]


index = faiss.IndexFlatIP(
    dimension
)

In [32]:
index.add(final_embeddings)

In [33]:
print(index.ntotal)

50674

In [34]:
df_songs[
    df_songs["name"].str.contains(
        "Blinding",
        case=False,
        na=False
    )
][["name","artist"]]

                                      name                  artist
1146                              Blinding  Florence + the Machine
19991                   The Blinding Light        August Burns Red
24256  Blinding Tears Will Break The Skies                 Trivium
25035          The Blinding of False Light          As I Lay Dying
31789                         The Blinding            Babyshambles
35142              Into The Blinding Light                Thursday